### ISSUE TITLE
data obtain

### ISSUE THREAD

**Issue by AndAvia** [RasmussenLab/vCentenarian#1]
I would like to obtain the Virus genomes and annotation data for this article.This site (https://zenodo.org/record/6579480#.Yo3xHZNBweY) won't open, can you provide me with a way to download it, or some other way to do it, appreciate it!

**Comment by enryH** [comment]
For me the link works you posted: https://zenodo.org/records/6579480#.Yo3xHZNBweY 

Are you behind a firewall?

**Comment by AndAvia** [comment]
> For me the link works you posted: https://zenodo.org/records/6579480#.Yo3xHZNBweY
> 
> Are you behind a firewall?

I changed the network and it opens now. Thanks.

**Comment by enryH** [comment]
perfect:)

**Comment by AndAvia** [comment]
I want to do phylogenetic tree, can you provide me with the files count_hmm_hits.py, strand_switch.py, master_table.py, virus_classify.py from the literature analysis process, there are no such scripts in the code folder, if you can provide me with them I would be very grateful!
